### ISSUE TITLE
Dashboard?

### ISSUE THREAD

**Issue by andrea-ligios** [hpgrahsl/voxxed-days-ticino-2018#1]
Hi, it's a very nice talk, I've been happy to be there.

Out of curiosity, is the Angular Dashboard also available on GitHub?

I know it's not your, I'd simply like to know if it's been released somewhere or not.

Thank you,
Cheers

**Comment by hpgrahsl** [comment]
@andrea-ligios glad to hear you liked the talk :)

the angular SPA is not in the repo, as I said a colleague of mine quickly wrote it some time ago. but AFAIK it's nothing special or complex. it's consuming from the endpoints and does a little bit of styling to get a nicer look & feel. but I can try to get it if you absolutely would need it.

**Comment by andrea-ligios** [comment]
Well, it's not a need, I'd simply like to take a look at it if possible. Thank you for answering BTW
